export const CREATE_EVENT = "CREATE_EVENT";
export const CREATE_EVENT_LOADING = "CREATE_EVENT_LOADING";
export const CREATE_EVENT_ERROR = "CREATE_EVENT_ERROR";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
